// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQkE7G8RXDqY3ckCc-5WehtLrBtiNUnsE',
    appId: '1:151881927593:web:421b4be2fdb4ff3bac92b8',
    messagingSenderId: '151881927593',
    projectId: 'ecommerce-4211',
    authDomain: 'ecommerce-4211.firebaseapp.com',
    storageBucket: 'ecommerce-4211.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiux2RZmC0pkr6QB_kCR3uhXXz5cpA1xg',
    appId: '1:151881927593:android:e344b057899ca0f7ac92b8',
    messagingSenderId: '151881927593',
    projectId: 'ecommerce-4211',
    storageBucket: 'ecommerce-4211.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGWk3c5uYNwGSxT6iW98JXxqplDFGUx5c',
    appId: '1:151881927593:ios:09967b2dde6bba9dac92b8',
    messagingSenderId: '151881927593',
    projectId: 'ecommerce-4211',
    storageBucket: 'ecommerce-4211.appspot.com',
    iosBundleId: 'com.ramazangokmen.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGWk3c5uYNwGSxT6iW98JXxqplDFGUx5c',
    appId: '1:151881927593:ios:09967b2dde6bba9dac92b8',
    messagingSenderId: '151881927593',
    projectId: 'ecommerce-4211',
    storageBucket: 'ecommerce-4211.appspot.com',
    iosBundleId: 'com.ramazangokmen.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQkE7G8RXDqY3ckCc-5WehtLrBtiNUnsE',
    appId: '1:151881927593:web:df1df0b298fbf0b6ac92b8',
    messagingSenderId: '151881927593',
    projectId: 'ecommerce-4211',
    authDomain: 'ecommerce-4211.firebaseapp.com',
    storageBucket: 'ecommerce-4211.appspot.com',
  );
}
